//
// Created by said2 on 17-11-2021.
//

#ifndef DOODLEJUMP_SAID_YANDARBIEV_STOPWATCH_H
#define DOODLEJUMP_SAID_YANDARBIEV_STOPWATCH_H


class Stopwatch {

};


#endif //DOODLEJUMP_SAID_YANDARBIEV_STOPWATCH_H
